"""Group the exported functions into the R package's documentation families. The documentation site's reference and the documentation test read these groups."""

FAMILIES = {
    "import": {
        "title": "Import data",
        "desc": "Load and shape raw survey exports.",
        "names": ["parse_filename", "read_folder", "select_prefix", "select_suffix"],
    },
    "select": {
        "title": "Select columns",
        "desc": "The Python form of the tidyselect helpers R users pass to ezrsurvey.",
        "names": ["all_of", "any_of", "contains", "ends_with", "everything", "is_numeric", "starts_with", "where"],
    },
    "recode": {
        "title": "Clean & recode",
        "desc": "Turn messy survey columns into tidy, analysis-ready variables.",
        "names": [
            "add_region",
            "bin_numeric",
            "clean_label",
            "drop_items",
            "ensure_numeric",
            "generation_scheme",
            "na_blank",
            "nps_group",
            "recode_age",
            "recode_generation",
            "recode_likert",
            "recode_region",
            "recode_subregion",
            "split_multi",
        ],
    },
    "summaries": {
        "title": "Summarise",
        "desc": "Percentages, summaries and cross-tabulations in one line.",
        "names": [
            "calc_percentage",
            "calc_percentage_batch",
            "calc_percentage_multi",
            "calc_summary",
            "clear_checkpoints",
            "crosstab",
            "crosstab_banner",
        ],
    },
    "weighting": {
        "title": "Weighting",
        "desc": "Post-stratification / raking applied automatically to the summaries.",
        "names": ["clear_weights", "clear_weights_cache", "get_weights", "has_weights", "set_weights", "weight_vector"],
    },
    "modelling": {
        "title": "Model",
        "desc": "NPS and importance/performance modelling.",
        "names": ["calc_importance", "calc_nps", "ipm_model"],
    },
    "compare": {
        "title": "Compare",
        "desc": "Differences between events, waves or segments.",
        "names": ["compare_values", "plot_diff"],
    },
    "diagnostics": {
        "title": "Diagnostics",
        "desc": "Sampling precision and standard errors.",
        "names": ["diagnose", "margin_of_error", "precision_summary", "rse", "rse_rating", "se_mean", "se_prop"],
    },
    "comments": {
        "title": "Comments",
        "desc": "Select illustrative open-text comments.",
        "names": ["sample_comments", "sample_comments_diverse"],
    },
    "currency": {
        "title": "Currency",
        "desc": "Convert monetary amounts between currencies.",
        "names": ["add_currency", "convert_currency", "list_currencies"],
    },
    "plots": {
        "title": "Plots",
        "desc": "Presentation-ready static charts.",
        "names": [
            "plot_bars",
            "plot_gauges",
            "plot_ipm",
            "plot_nps",
            "plot_nps_gauge",
            "plot_quotes_tree",
            "plot_rating_grid",
            "plot_stacked_rating",
        ],
    },
    "brand": {
        "title": "Brand",
        "desc": "Adopt an organisation's colours and typefaces for every chart.",
        "names": [
            "brand_info",
            "clear_brand",
            "pal_brand",
            "scale_color_brand",
            "scale_colour_brand",
            "scale_fill_brand",
            "use_brand",
        ],
    },
    "themes": {
        "title": "Themes & palettes",
        "desc": "Visual identity for every chart.",
        "names": [
            "pal_neutral",
            "pal_nps",
            "pal_rating",
            "pal_sequential_blue",
            "scale_color_rating",
            "scale_colour_rating",
            "scale_fill_nps",
            "scale_fill_rating",
            "theme_ezrsurvey",
            "theme_ezrsurvey_x",
            "theme_ezrsurvey_xy",
            "theme_ezrsurvey_y",
            "theme_transparent",
        ],
    },
    "decisions": {
        "title": "Decisions",
        "desc": "Decision-band annotations.",
        "names": [
            "annotate_bands",
            "bands_nps",
            "bands_nps_score",
            "bands_rating_3",
            "bands_rating_5",
            "mark_value",
            "rescale_bands",
        ],
    },
    "scales": {
        "title": "Scales",
        "desc": "Tidy axis ceilings and percentage labels.",
        "names": ["label_pct", "nice_max", "scale_y_pct"],
    },
    "save": {
        "title": "Save",
        "desc": "Export tables and charts.",
        "names": ["export_summary_xlsx", "export_xlsx", "save_data", "save_output", "save_plot"],
    },
    "reporting": {
        "title": "Report",
        "desc": "Decks, Word documents and Quarto reports.",
        "names": [
            "example_report",
            "list_report_templates",
            "report_add_plot",
            "report_add_slide",
            "report_add_table",
            "report_add_text",
            "report_deck",
            "report_layouts",
            "report_new",
            "report_save",
            "report_section",
            "report_slide",
            "report_title_slide",
            "scaffold_report",
        ],
    },
    "config": {
        "title": "Configuration",
        "desc": "Options, the default dataset, reusable orders and profiles.",
        "names": [
            "apply_order",
            "clear_dataset",
            "dataset_vars",
            "edit_ezrsurvey_profile",
            "ezrsurvey_options",
            "ezrsurvey_profile_paths",
            "get_dataset",
            "get_order",
            "has_dataset",
            "list_orders",
            "load_ezrsurvey_profile",
            "order_for",
            "register_order",
            "register_order_presets",
            "remove_order",
            "reset_ezrsurvey_options",
            "save_ezrsurvey_profile",
            "use_dataset",
            "use_ezrsurvey_profile",
        ],
    },
    "data": {
        "title": "Datasets",
        "desc": "The simulated surveys and lookup tables the examples use.",
        "names": ["country_region", "currency_rates", "podracing_survey", "shopping_survey"],
    },
}
